# Настройки логирования
log: 
    # уровень логирования (error / warn / info / debug)
    level: debug
    # путь к файлу логов
    file: "parser.log"
    # формат логирования
    format_JSON: true

# Настройки веб-сервера
# host и port на котором должен слушать web-сервер
http_host: "0.0.0.0"
http_port: "7777"
path_tmp: "tmp_files"